function G = HomSphereGradient( R, sigma, srcpnts, dipmom, obspnts )
% HomSphereGradient calculates the electric potential gradient in M points
% inside a homogeneous sphere due to N current dipoles, making use of the
% analytical gradiet of the formula given in:
% Yao, "Electric Potential Produced by a Dipole in a Homogeneous Conducting
% Sphere", IEEE Transactions on Biomedical Engineering, 47(7) (2000),
% pp. 964-966.
%
% Input arguments:
% R        =  sphere radius [m].
% sigma    =  sphere electric conductivity [S/m].
% srcpnts  =  Nx3 matrix of source dipoles coordinates [m].
% dipmom   =  Nx3 matrix of dipole moments components [A*m].
% obspnts  =  Mx3 matrix of observation points coordinates [m].
%
% Output:
% G        =  Mx3 vector of gradient components at observation points [V/m].

M = size(obspnts,1); N = size(srcpnts,1);
G = zeros(M,3);

R2 = R^2;   R5 = R^5;   R7 = R^7;

for i = 1:M
    r = obspnts(i,1)*obspnts(i,1) + ...
        obspnts(i,2)*obspnts(i,2) + ...
        obspnts(i,3)*obspnts(i,3);
    for j = 1:N
        dxx0 = obspnts(i,1) - srcpnts(j,1);
        dyy0 = obspnts(i,2) - srcpnts(j,2);
        dzz0 = obspnts(i,3) - srcpnts(j,3);
        dist = dxx0*dxx0 + dyy0*dyy0 + dzz0*dzz0;
        dist3_2 = dist^(3/2);   dist5_2 = dist^(5/2);
        r0 = srcpnts(j,1)*srcpnts(j,1) + ...
             srcpnts(j,2)*srcpnts(j,2) + ...
             srcpnts(j,3)*srcpnts(j,3);
        dot = obspnts(i,1)*srcpnts(j,1) + ...
              obspnts(i,2)*srcpnts(j,2) + ...
              obspnts(i,3)*srcpnts(j,3);
        a = 1 - (2*dot - (r*r0)/R2)/R2;
        AA = a^(1/2);
        BB = a^(3/2);
        CC = a^(5/2);
        
        Gx_x = dipmom(j,1)*(1/dist3_2 - (3*dxx0*dxx0)/dist5_2 - ...
            (2*obspnts(i,1)*srcpnts(j,1) - R2)/(R5*BB) + (obspnts(i,2)*srcpnts(j,2) + ...
            obspnts(i,3)*srcpnts(j,3) + R2*(AA - dot/R2 + 1) - ...
            R2*obspnts(i,1)*(srcpnts(j,1)/R2 + (2*srcpnts(j,1) - ...
            (2*obspnts(i,1)*r0)/R2)/(2*R2*AA)))/(R5*AA*(AA - dot/R2 + 1)) + ...
            (3*(R2*obspnts(i,1) - srcpnts(j,1)*r)*(2*srcpnts(j,1) - ...
            (2*obspnts(i,1)*r0)/R2))/(2*R7*CC) + ((2*srcpnts(j,1) - ...
            (2*obspnts(i,1)*r0)/R2)*(obspnts(i,1)*dot - srcpnts(j,1)*r + ...
            R2*obspnts(i,1)*(AA - dot/R2 + 1)))/(2*R7*BB*(AA - dot/R2 + 1)) + ...
            ((srcpnts(j,1)/R2 + (2*srcpnts(j,1) - ...
            (2*obspnts(i,1)*r0)/R2)/(2*R2*AA))*(obspnts(i,1)*dot - srcpnts(j,1)*r + ...
            R2*obspnts(i,1)*(AA - dot/R2 + 1)))/(R5*AA*(AA - dot/R2 + 1)^2));
        
        Gy_x = -dipmom(j,2)*((3*dxx0*dyy0)/dist5_2 + ...
            (2*obspnts(i,1)*srcpnts(j,2))/(R5*BB) - ...
            (3*(2*srcpnts(j,1) - (2*obspnts(i,1)*r0)/R2)*(R2*obspnts(i,2) - ...
            srcpnts(j,2)*r))/(2*R7*CC) + (2*obspnts(i,1)*srcpnts(j,2) - ...
            srcpnts(j,1)*obspnts(i,2) + R2*obspnts(i,2)*(srcpnts(j,1)/R2 + (2*srcpnts(j,1) - ...
            (2*obspnts(i,1)*r0)/R2)/(2*R2*AA)))/(R5*AA*(AA - dot/R2 + 1)) - ...
            ((2*srcpnts(j,1) - (2*obspnts(i,1)*r0)/R2)*(obspnts(i,2)*dot - srcpnts(j,2)*r + ...
            R2*obspnts(i,2)*(AA - dot/R2 + 1)))/(2*R7*BB*(AA - dot/R2 + 1)) - ...
            ((srcpnts(j,1)/R2 + (2*srcpnts(j,1) - ...
            (2*obspnts(i,1)*r0)/R2)/(2*R2*AA))*(obspnts(i,2)*dot - srcpnts(j,2)*r + ...
            R2*obspnts(i,2)*(AA - dot/R2 + 1)))/(R5*AA*(AA - dot/R2 + 1)^2));
        
        Gz_x = -dipmom(j,3)*((3*dxx0*dzz0)/dist5_2 + ...
            (2*obspnts(i,1)*srcpnts(j,3))/(R5*BB) - ...
            (3*(2*srcpnts(j,1) - (2*obspnts(i,1)*r0)/R2)*(R2*obspnts(i,3) - ...
            srcpnts(j,3)*r))/(2*R7*CC) + (2*obspnts(i,1)*srcpnts(j,3) - ...
            srcpnts(j,1)*obspnts(i,3) + R2*obspnts(i,3)*(srcpnts(j,1)/R2 + (2*srcpnts(j,1) - ...
            (2*obspnts(i,1)*r0)/R2)/(2*R2*AA)))/(R5*AA*(AA - dot/R2 + 1)) - ...
            ((2*srcpnts(j,1) - (2*obspnts(i,1)*r0)/R2)*(obspnts(i,3)*dot - srcpnts(j,3)*r + ...
            R2*obspnts(i,3)*(AA - dot/R2 + 1)))/(2*R7*BB*(AA - dot/R2 + 1)) - ...
            ((srcpnts(j,1)/R2 + (2*srcpnts(j,1) - ...
            (2*obspnts(i,1)*r0)/R2)/(2*R2*AA))*(obspnts(i,3)*dot - srcpnts(j,3)*r + ...
            R2*obspnts(i,3)*(AA - dot/R2 + 1)))/(R5*AA*(AA - dot/R2 + 1)^2));
        
        
        Gx_y = -dipmom(j,1)*((3*dyy0*dxx0)/dist5_2 + ...
            (2*srcpnts(j,1)*obspnts(i,2))/(R5*BB) - ....
            (3*(R2*obspnts(i,1) - srcpnts(j,1)*r)*(2*srcpnts(j,2) - ...
            (2*obspnts(i,2)*r0)/R2))/(2*R7*CC) + (2*srcpnts(j,1)*obspnts(i,2) - ...
            obspnts(i,1)*srcpnts(j,2) + R2*obspnts(i,1)*(srcpnts(j,2)/R2 + (2*srcpnts(j,2) - ...
            (2*obspnts(i,2)*r0)/R2)/(2*R2*AA)))/(R5*AA*(AA - dot/R2 + 1)) - ...
            ((2*srcpnts(j,2) - (2*obspnts(i,2)*r0)/R2)*(obspnts(i,1)*dot - srcpnts(j,1)*r + ...
            R2*obspnts(i,1)*(AA - dot/R2 + 1)))/(2*R7*BB*(AA - dot/R2 + 1)) - ...
            ((srcpnts(j,2)/R2 + (2*srcpnts(j,2) - ...
            (2*obspnts(i,2)*r0)/R2)/(2*R2*AA))*(obspnts(i,1)*dot - srcpnts(j,1)*r + ...
            R2*obspnts(i,1)*(AA - dot/R2 + 1)))/(R5*AA*(AA - dot/R2 + 1)^2));
        
        Gy_y = dipmom(j,2)*(1/dist3_2 - (3*dyy0*dyy0)/dist5_2 - ...
            (2*obspnts(i,2)*srcpnts(j,2) - R2)/(R5*BB) + ...
            (obspnts(i,1)*srcpnts(j,1) + obspnts(i,3)*srcpnts(j,3) + R2*(AA - dot/R2 + 1) - ...
            R2*obspnts(i,2)*(srcpnts(j,2)/R2 + (2*srcpnts(j,2) - ...
            (2*obspnts(i,2)*r0)/R2)/(2*R2*AA)))/(R5*AA*(AA - dot/R2 + 1)) + ...
            (3*(R2*obspnts(i,2) - srcpnts(j,2)*r)*(2*srcpnts(j,2) - ...
            (2*obspnts(i,2)*r0)/R2))/(2*R7*CC) + ((2*srcpnts(j,2) - ...
            (2*obspnts(i,2)*r0)/R2)*(obspnts(i,2)*dot - srcpnts(j,2)*r + ...
            R2*obspnts(i,2)*(AA - dot/R2 + 1)))/(2*R7*BB*(AA - dot/R2 + 1)) + ...
            ((srcpnts(j,2)/R2 + (2*srcpnts(j,2) - ...
            (2*obspnts(i,2)*r0)/R2)/(2*R2*AA))*(obspnts(i,2)*dot - srcpnts(j,2)*r + ...
            R2*obspnts(i,2)*(AA - dot/R2 + 1)))/(R5*AA*(AA - dot/R2 + 1)^2));
        
        Gz_y = -dipmom(j,3)*((3*dyy0*dzz0)/dist5_2 + ...
            (2*obspnts(i,2)*srcpnts(j,3))/(R5*BB) - ...
            (3*(2*srcpnts(j,2) - (2*obspnts(i,2)*r0)/R2)*(R2*obspnts(i,3) - ...
            srcpnts(j,3)*r))/(2*R7*CC) + (2*obspnts(i,2)*srcpnts(j,3) - ...
            srcpnts(j,2)*obspnts(i,3) + R2*obspnts(i,3)*(srcpnts(j,2)/R2 + (2*srcpnts(j,2) - ...
            (2*obspnts(i,2)*r0)/R2)/(2*R2*AA)))/(R5*AA*(AA - dot/R2 + 1)) - ...
            ((2*srcpnts(j,2) - (2*obspnts(i,2)*r0)/R2)*(obspnts(i,3)*dot - srcpnts(j,3)*r + ...
            R2*obspnts(i,3)*(AA - dot/R2 + 1)))/(2*R7*BB*(AA - dot/R2 + 1)) - ...
            ((srcpnts(j,2)/R2 + (2*srcpnts(j,2) - ...
            (2*obspnts(i,2)*r0)/R2)/(2*R2*AA))*(obspnts(i,3)*dot - srcpnts(j,3)*r + ...
            R2*obspnts(i,3)*(AA - dot/R2 + 1)))/(R5*AA*(AA - dot/R2 + 1)^2));
        
        
        Gx_z = -dipmom(j,1)*((3*dzz0*dxx0)/dist5_2 + ...
            (2*srcpnts(j,1)*obspnts(i,3))/(R5*BB) - ...
            (3*(R2*obspnts(i,1) - srcpnts(j,1)*r)*(2*srcpnts(j,3) - ...
            (2*obspnts(i,3)*r0)/R2))/(2*R7*CC) + (2*srcpnts(j,1)*obspnts(i,3) - ...
            obspnts(i,1)*srcpnts(j,3) + R2*obspnts(i,1)*(srcpnts(j,3)/R2 + (2*srcpnts(j,3) - ...
            (2*obspnts(i,3)*r0)/R2)/(2*R2*AA)))/(R5*AA*(AA - dot/R2 + 1)) - ...
            ((2*srcpnts(j,3) - (2*obspnts(i,3)*r0)/R2)*(obspnts(i,1)*dot - srcpnts(j,1)*r + ...
            R2*obspnts(i,1)*(AA - dot/R2 + 1)))/(2*R7*BB*(AA - dot/R2 + 1)) - ...
            ((srcpnts(j,3)/R2 + (2*srcpnts(j,3) - ...
            (2*obspnts(i,3)*r0)/R2)/(2*R2*AA))*(obspnts(i,1)*dot - srcpnts(j,1)*r + ...
            R2*obspnts(i,1)*(AA - dot/R2 + 1)))/(R5*AA*(AA - dot/R2 + 1)^2));
        
        Gy_z = -dipmom(j,2)*((3*dzz0*dyy0)/dist5_2 + ...
            (2*srcpnts(j,2)*obspnts(i,3))/(R5*BB) - ...
            (3*(R2*obspnts(i,2) - srcpnts(j,2)*r)*(2*srcpnts(j,3) - ...
            (2*obspnts(i,3)*r0)/R2))/(2*R7*CC) + (2*srcpnts(j,2)*obspnts(i,3) - ...
            obspnts(i,2)*srcpnts(j,3) + R2*obspnts(i,2)*(srcpnts(j,3)/R2 + (2*srcpnts(j,3) - ...
            (2*obspnts(i,3)*r0)/R2)/(2*R2*AA)))/(R5*AA*(AA - dot/R2 + 1)) - ...
            ((2*srcpnts(j,3) - (2*obspnts(i,3)*r0)/R2)*(obspnts(i,2)*dot - srcpnts(j,2)*r + ...
            R2*obspnts(i,2)*(AA - dot/R2 + 1)))/(2*R7*BB*(AA - dot/R2 + 1)) - ...
            ((srcpnts(j,3)/R2 + (2*srcpnts(j,3) - ...
            (2*obspnts(i,3)*r0)/R2)/(2*R2*AA))*(obspnts(i,2)*dot - srcpnts(j,2)*r + ...
            R2*obspnts(i,2)*(AA - dot/R2 + 1)))/(R5*AA*(AA - dot/R2 + 1)^2));
        
        Gz_z = dipmom(j,3)*(1/dist3_2 - (3*dzz0*dzz0)/dist5_2 - ...
            (2*obspnts(i,3)*srcpnts(j,3) - R2)/(R5*BB) + ...
            (obspnts(i,1)*srcpnts(j,1) + obspnts(i,2)*srcpnts(j,2) + R2*(AA - dot/R2 + 1) - ...
            R2*obspnts(i,3)*(srcpnts(j,3)/R2 + (2*srcpnts(j,3) - ...
            (2*obspnts(i,3)*r0)/R2)/(2*R2*AA)))/(R5*AA*(AA - dot/R2 + 1)) + ...
            (3*(R2*obspnts(i,3) - srcpnts(j,3)*r)*(2*srcpnts(j,3) - ...
            (2*obspnts(i,3)*r0)/R2))/(2*R7*CC) + ((2*srcpnts(j,3) - ...
            (2*obspnts(i,3)*r0)/R2)*(obspnts(i,3)*dot - srcpnts(j,3)*r + ...
            R2*obspnts(i,3)*(AA - dot/R2 + 1)))/(2*R7*BB*(AA - dot/R2 + 1)) + ...
            ((srcpnts(j,3)/R2 + (2*srcpnts(j,3) - ...
            (2*obspnts(i,3)*r0)/R2)/(2*R2*AA))*(obspnts(i,3)*dot - srcpnts(j,3)*r + ...
            R2*obspnts(i,3)*(AA - dot/R2 + 1)))/(R5*AA*(AA - dot/R2 + 1)^2));
        
        
        G(i,:) = G(i,:) + ...
            [Gx_x + Gy_x + Gz_x, Gx_y + Gy_y + Gz_y, Gx_z + Gy_z + Gz_z];
    end
end

G = G/(4*pi*sigma);

end